# Datasource settings for the Postgresql database
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:18000/jore4?stringtype=unspecified
db.min.connections=0
db.max.connections=5
db.username=jore4
db.password=jore4

spring.flyway.enabled=false
spring.flyway.clean-disabled=false

jooq.sql.dialect=POSTGRES
jooq.generator.input.schema=digiroad
