---
version: "3.8"
services:
  postgis:
    image: pgrouting/pgrouting:13-3.1-3.2.0
    container_name: jore4-map-matching-database
    restart: "unless-stopped"
    networks:
      - jore4
    ports:
      - "127.0.0.1:18000:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 30s
      start_period: 5s
      timeout: 10s
      retries: 3

  spring-boot-server:
    build:
      context: "."
      dockerfile: "docker-spring-boot/Dockerfile"
    container_name: jore4-map-matching-backend
    depends_on:
      postgis:
        condition: "service_healthy"
    restart: "unless-stopped"
    networks:
      - jore4
    ports:
      - "127.0.0.1:3200:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgis:5432/${POSTGRES_DB}?stringtype=unspecified
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}

networks:
  jore4:
    name: jore4_network
