/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model.tables.records;


import fi.hsl.jore4.mapmatching.model.tables.TrafficFlowDirection;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The possible directions of traffic flow on infrastructure links. Using code
 * values from Digiroad codeset.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrafficFlowDirectionRecord extends UpdatableRecordImpl<TrafficFlowDirectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>routing.traffic_flow_direction.traffic_flow_direction_type</code>.
     * Numeric enum value for direction of traffic flow. The code value
     * originates from Digiroad codeset.
     */
    public void setTrafficFlowDirectionType(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>routing.traffic_flow_direction.traffic_flow_direction_type</code>.
     * Numeric enum value for direction of traffic flow. The code value
     * originates from Digiroad codeset.
     */
    public Integer getTrafficFlowDirectionType() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>routing.traffic_flow_direction.traffic_flow_direction_name</code>.
     * The short name for direction of traffic flow. The text value originates
     * from the JORE4 database schema.
     */
    public void setTrafficFlowDirectionName(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>routing.traffic_flow_direction.traffic_flow_direction_name</code>.
     * The short name for direction of traffic flow. The text value originates
     * from the JORE4 database schema.
     */
    public String getTrafficFlowDirectionName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>routing.traffic_flow_direction.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>routing.traffic_flow_direction.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrafficFlowDirectionRecord
     */
    public TrafficFlowDirectionRecord() {
        super(TrafficFlowDirection.TRAFFIC_FLOW_DIRECTION);
    }

    /**
     * Create a detached, initialised TrafficFlowDirectionRecord
     */
    public TrafficFlowDirectionRecord(Integer trafficFlowDirectionType, String trafficFlowDirectionName, String description) {
        super(TrafficFlowDirection.TRAFFIC_FLOW_DIRECTION);

        setTrafficFlowDirectionType(trafficFlowDirectionType);
        setTrafficFlowDirectionName(trafficFlowDirectionName);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
