# Datasource settings for the Postgresql database
db.driver=org.postgresql.Driver
db.url=
db.min.connections=0
db.max.connections=5
db.username=
db.password=

spring.flyway.enabled=true
spring.flyway.clean-disabled=true
