/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model.tables;


import fi.hsl.jore4.mapmatching.model.Keys;
import fi.hsl.jore4.mapmatching.model.Routing;
import fi.hsl.jore4.mapmatching.model.tables.VehicleType.VehicleTypePath;
import fi.hsl.jore4.mapmatching.model.tables.records.VehicleModeRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * The vehicle modes from Transmodel:
 * https://www.transmodel-cen.eu/model/index.htm?goto=1:6:1:283
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VehicleMode extends TableImpl<VehicleModeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>routing.vehicle_mode</code>
     */
    public static final VehicleMode VEHICLE_MODE = new VehicleMode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VehicleModeRecord> getRecordType() {
        return VehicleModeRecord.class;
    }

    /**
     * The column <code>routing.vehicle_mode.vehicle_mode</code>. The vehicle
     * mode from Transmodel:
     * https://www.transmodel-cen.eu/model/index.htm?goto=1:6:1:283
     */
    public final TableField<VehicleModeRecord, String> VEHICLE_MODE_ = createField(DSL.name("vehicle_mode"), SQLDataType.CLOB.nullable(false), this, "The vehicle mode from Transmodel: https://www.transmodel-cen.eu/model/index.htm?goto=1:6:1:283");

    private VehicleMode(Name alias, Table<VehicleModeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VehicleMode(Name alias, Table<VehicleModeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("The vehicle modes from Transmodel: https://www.transmodel-cen.eu/model/index.htm?goto=1:6:1:283"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>routing.vehicle_mode</code> table reference
     */
    public VehicleMode(String alias) {
        this(DSL.name(alias), VEHICLE_MODE);
    }

    /**
     * Create an aliased <code>routing.vehicle_mode</code> table reference
     */
    public VehicleMode(Name alias) {
        this(alias, VEHICLE_MODE);
    }

    /**
     * Create a <code>routing.vehicle_mode</code> table reference
     */
    public VehicleMode() {
        this(DSL.name("vehicle_mode"), null);
    }

    public <O extends Record> VehicleMode(Table<O> path, ForeignKey<O, VehicleModeRecord> childPath, InverseForeignKey<O, VehicleModeRecord> parentPath) {
        super(path, childPath, parentPath, VEHICLE_MODE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VehicleModePath extends VehicleMode implements Path<VehicleModeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VehicleModePath(Table<O> path, ForeignKey<O, VehicleModeRecord> childPath, InverseForeignKey<O, VehicleModeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VehicleModePath(Name alias, Table<VehicleModeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VehicleModePath as(String alias) {
            return new VehicleModePath(DSL.name(alias), this);
        }

        @Override
        public VehicleModePath as(Name alias) {
            return new VehicleModePath(alias, this);
        }

        @Override
        public VehicleModePath as(Table<?> alias) {
            return new VehicleModePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Routing.ROUTING;
    }

    @Override
    public UniqueKey<VehicleModeRecord> getPrimaryKey() {
        return Keys.VEHICLE_MODE_PKEY;
    }

    private transient VehicleTypePath _vehicleType;

    /**
     * Get the implicit to-many join path to the
     * <code>routing.vehicle_type</code> table
     */
    public VehicleTypePath vehicleType() {
        if (_vehicleType == null)
            _vehicleType = new VehicleTypePath(this, null, Keys.VEHICLE_TYPE__VEHICLE_TYPE_BELONGING_TO_VEHICLE_MODE_FKEY.getInverseKey());

        return _vehicleType;
    }

    @Override
    public VehicleMode as(String alias) {
        return new VehicleMode(DSL.name(alias), this);
    }

    @Override
    public VehicleMode as(Name alias) {
        return new VehicleMode(alias, this);
    }

    @Override
    public VehicleMode as(Table<?> alias) {
        return new VehicleMode(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleMode rename(String name) {
        return new VehicleMode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleMode rename(Name name) {
        return new VehicleMode(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleMode rename(Table<?> name) {
        return new VehicleMode(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleMode where(Condition condition) {
        return new VehicleMode(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleMode where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleMode where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleMode where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleMode where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleMode where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleMode where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleMode where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleMode whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleMode whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
