/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model;


import fi.hsl.jore4.mapmatching.model.tables.DrLinkki;
import fi.hsl.jore4.mapmatching.model.tables.DrLinkkiVerticesPgr;
import fi.hsl.jore4.mapmatching.model.tables.DrPysakki;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routing extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>routing</code>
     */
    public static final Routing ROUTING = new Routing();

    /**
     * The table <code>routing.dr_linkki</code>.
     */
    public final DrLinkki DR_LINKKI = DrLinkki.DR_LINKKI;

    /**
     * The table <code>routing.dr_linkki_vertices_pgr</code>.
     */
    public final DrLinkkiVerticesPgr DR_LINKKI_VERTICES_PGR = DrLinkkiVerticesPgr.DR_LINKKI_VERTICES_PGR;

    /**
     * The table <code>routing.dr_pysakki</code>.
     */
    public final DrPysakki DR_PYSAKKI = DrPysakki.DR_PYSAKKI;

    /**
     * No further instances allowed
     */
    private Routing() {
        super("routing", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.DR_LINKKI_VERTICES_PGR_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DrLinkki.DR_LINKKI,
            DrLinkkiVerticesPgr.DR_LINKKI_VERTICES_PGR,
            DrPysakki.DR_PYSAKKI);
    }
}
