/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in routing.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>routing.infrastructure_link_vertices_pgr_id_seq</code>
     */
    public static final Sequence<Long> INFRASTRUCTURE_LINK_VERTICES_PGR_ID_SEQ = Internal.createSequence("infrastructure_link_vertices_pgr_id_seq", Routing.ROUTING, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
