/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model;


import fi.hsl.jore4.mapmatching.model.tables.DrLinkki;
import fi.hsl.jore4.mapmatching.model.tables.DrLinkkiVerticesPgr;


/**
 * Convenience access to all tables in routing.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>routing.dr_linkki</code>.
     */
    public static final DrLinkki DR_LINKKI = DrLinkki.DR_LINKKI;

    /**
     * The table <code>routing.dr_linkki_vertices_pgr</code>.
     */
    public static final DrLinkkiVerticesPgr DR_LINKKI_VERTICES_PGR = DrLinkkiVerticesPgr.DR_LINKKI_VERTICES_PGR;
}
