/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model;


import fi.hsl.jore4.mapmatching.model.tables.InfrastructureLink;
import fi.hsl.jore4.mapmatching.model.tables.InfrastructureLinkSafelyTraversedByVehicleType;
import fi.hsl.jore4.mapmatching.model.tables.InfrastructureLinkVerticesPgr;
import fi.hsl.jore4.mapmatching.model.tables.InfrastructureSource;
import fi.hsl.jore4.mapmatching.model.tables.PublicTransportStop;
import fi.hsl.jore4.mapmatching.model.tables.TrafficFlowDirection;
import fi.hsl.jore4.mapmatching.model.tables.VehicleMode;
import fi.hsl.jore4.mapmatching.model.tables.VehicleType;


/**
 * Convenience access to all tables in routing.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The infrastructure links, e.g. road or rail elements:
     * https://www.transmodel-cen.eu/model/index.htm?goto=2:1:1:1:453
     */
    public static final InfrastructureLink INFRASTRUCTURE_LINK = InfrastructureLink.INFRASTRUCTURE_LINK;

    /**
     * Which infrastructure links are safely traversed by which vehicle types?
     */
    public static final InfrastructureLinkSafelyTraversedByVehicleType INFRASTRUCTURE_LINK_SAFELY_TRAVERSED_BY_VEHICLE_TYPE = InfrastructureLinkSafelyTraversedByVehicleType.INFRASTRUCTURE_LINK_SAFELY_TRAVERSED_BY_VEHICLE_TYPE;

    /**
     * Topology nodes created for infrastructure links by pgRougting
     */
    public static final InfrastructureLinkVerticesPgr INFRASTRUCTURE_LINK_VERTICES_PGR = InfrastructureLinkVerticesPgr.INFRASTRUCTURE_LINK_VERTICES_PGR;

    /**
     * The enumerated sources for infrastructure network entities
     */
    public static final InfrastructureSource INFRASTRUCTURE_SOURCE = InfrastructureSource.INFRASTRUCTURE_SOURCE;

    /**
     * The public transport stops imported from Digiroad export
     */
    public static final PublicTransportStop PUBLIC_TRANSPORT_STOP = PublicTransportStop.PUBLIC_TRANSPORT_STOP;

    /**
     * The possible directions of traffic flow on infrastructure links. Using
     * code values from Digiroad codeset.
     */
    public static final TrafficFlowDirection TRAFFIC_FLOW_DIRECTION = TrafficFlowDirection.TRAFFIC_FLOW_DIRECTION;

    /**
     * The vehicle modes from Transmodel:
     * https://www.transmodel-cen.eu/model/index.htm?goto=1:6:1:283
     */
    public static final VehicleMode VEHICLE_MODE = VehicleMode.VEHICLE_MODE;

    /**
     * The vehicle types from Transmodel:
     * https://www.transmodel-cen.eu/model/index.htm?goto=1:6:9:360
     */
    public static final VehicleType VEHICLE_TYPE = VehicleType.VEHICLE_TYPE;
}
