---
services:
  # empty database used in development while running service (instead of
  # "jore4-mapmatchingdb")
  jore4-mapmatchingdb-dev:
    extends:
      file: docker-compose.base.yml
      service: jore4-mapmatchingdb-base
    container_name: mapmatchingdb-dev
    ports:
      - "127.0.0.1:18000:5432"
    environment:
      - POSTGRES_USER=mapmatching
      - POSTGRES_PASSWORD=password

  # empty database for tests and jOOQ code generation
  jore4-mapmatchingdb-test:
    extends:
      file: docker-compose.base.yml
      service: jore4-mapmatchingdb-base
    container_name: mapmatchingdb-test
    ports:
      - "127.0.0.1:20000:5432"
    environment:
      - POSTGRES_USER=mapmatching
      - POSTGRES_PASSWORD=password
      - SKIP_SET_VARIABLE_SECRET_OVERRIDE=true
