/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model.tables.records;


import fi.hsl.jore4.mapmatching.model.tables.DrLinkki;

import org.geolatte.geom.C2D;
import org.geolatte.geom.LineString;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrLinkkiRecord extends UpdatableRecordImpl<DrLinkkiRecord> implements Record14<Integer, String, Integer, Integer, Integer, Integer, String, String, String, Integer, Integer, Double, Double, LineString<C2D>> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>routing.dr_linkki.gid</code>.
     */
    public void setGid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.gid</code>.
     */
    public Integer getGid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>routing.dr_linkki.link_id</code>.
     */
    public void setLinkId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.link_id</code>.
     */
    public String getLinkId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>routing.dr_linkki.kuntakoodi</code>.
     */
    public void setKuntakoodi(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.kuntakoodi</code>.
     */
    public Integer getKuntakoodi() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>routing.dr_linkki.linkkityyp</code>.
     */
    public void setLinkkityyp(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.linkkityyp</code>.
     */
    public Integer getLinkkityyp() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>routing.dr_linkki.ajosuunta</code>.
     */
    public void setAjosuunta(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.ajosuunta</code>.
     */
    public Integer getAjosuunta() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>routing.dr_linkki.link_tila</code>.
     */
    public void setLinkTila(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.link_tila</code>.
     */
    public Integer getLinkTila() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>routing.dr_linkki.tienimi_su</code>.
     */
    public void setTienimiSu(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.tienimi_su</code>.
     */
    public String getTienimiSu() {
        return (String) get(6);
    }

    /**
     * Setter for <code>routing.dr_linkki.tienimi_ru</code>.
     */
    public void setTienimiRu(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.tienimi_ru</code>.
     */
    public String getTienimiRu() {
        return (String) get(7);
    }

    /**
     * Setter for <code>routing.dr_linkki.tienimi_sa</code>.
     */
    public void setTienimiSa(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.tienimi_sa</code>.
     */
    public String getTienimiSa() {
        return (String) get(8);
    }

    /**
     * Setter for <code>routing.dr_linkki.source</code>.
     */
    public void setSource(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.source</code>.
     */
    public Integer getSource() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>routing.dr_linkki.target</code>.
     */
    public void setTarget(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.target</code>.
     */
    public Integer getTarget() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>routing.dr_linkki.cost</code>.
     */
    public void setCost(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.cost</code>.
     */
    public Double getCost() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>routing.dr_linkki.reverse_cost</code>.
     */
    public void setReverseCost(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.reverse_cost</code>.
     */
    public Double getReverseCost() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>routing.dr_linkki.geom</code>.
     */
    public void setGeom(LineString<C2D> value) {
        set(13, value);
    }

    /**
     * Getter for <code>routing.dr_linkki.geom</code>.
     */
    public LineString<C2D> getGeom() {
        return (LineString<C2D>) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, String, Integer, Integer, Integer, Integer, String, String, String, Integer, Integer, Double, Double, LineString<C2D>> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, String, Integer, Integer, Integer, Integer, String, String, String, Integer, Integer, Double, Double, LineString<C2D>> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DrLinkki.DR_LINKKI.GID;
    }

    @Override
    public Field<String> field2() {
        return DrLinkki.DR_LINKKI.LINK_ID;
    }

    @Override
    public Field<Integer> field3() {
        return DrLinkki.DR_LINKKI.KUNTAKOODI;
    }

    @Override
    public Field<Integer> field4() {
        return DrLinkki.DR_LINKKI.LINKKITYYP;
    }

    @Override
    public Field<Integer> field5() {
        return DrLinkki.DR_LINKKI.AJOSUUNTA;
    }

    @Override
    public Field<Integer> field6() {
        return DrLinkki.DR_LINKKI.LINK_TILA;
    }

    @Override
    public Field<String> field7() {
        return DrLinkki.DR_LINKKI.TIENIMI_SU;
    }

    @Override
    public Field<String> field8() {
        return DrLinkki.DR_LINKKI.TIENIMI_RU;
    }

    @Override
    public Field<String> field9() {
        return DrLinkki.DR_LINKKI.TIENIMI_SA;
    }

    @Override
    public Field<Integer> field10() {
        return DrLinkki.DR_LINKKI.SOURCE;
    }

    @Override
    public Field<Integer> field11() {
        return DrLinkki.DR_LINKKI.TARGET;
    }

    @Override
    public Field<Double> field12() {
        return DrLinkki.DR_LINKKI.COST;
    }

    @Override
    public Field<Double> field13() {
        return DrLinkki.DR_LINKKI.REVERSE_COST;
    }

    @Override
    public Field<LineString<C2D>> field14() {
        return DrLinkki.DR_LINKKI.GEOM;
    }

    @Override
    public Integer component1() {
        return getGid();
    }

    @Override
    public String component2() {
        return getLinkId();
    }

    @Override
    public Integer component3() {
        return getKuntakoodi();
    }

    @Override
    public Integer component4() {
        return getLinkkityyp();
    }

    @Override
    public Integer component5() {
        return getAjosuunta();
    }

    @Override
    public Integer component6() {
        return getLinkTila();
    }

    @Override
    public String component7() {
        return getTienimiSu();
    }

    @Override
    public String component8() {
        return getTienimiRu();
    }

    @Override
    public String component9() {
        return getTienimiSa();
    }

    @Override
    public Integer component10() {
        return getSource();
    }

    @Override
    public Integer component11() {
        return getTarget();
    }

    @Override
    public Double component12() {
        return getCost();
    }

    @Override
    public Double component13() {
        return getReverseCost();
    }

    @Override
    public LineString<C2D> component14() {
        return getGeom();
    }

    @Override
    public Integer value1() {
        return getGid();
    }

    @Override
    public String value2() {
        return getLinkId();
    }

    @Override
    public Integer value3() {
        return getKuntakoodi();
    }

    @Override
    public Integer value4() {
        return getLinkkityyp();
    }

    @Override
    public Integer value5() {
        return getAjosuunta();
    }

    @Override
    public Integer value6() {
        return getLinkTila();
    }

    @Override
    public String value7() {
        return getTienimiSu();
    }

    @Override
    public String value8() {
        return getTienimiRu();
    }

    @Override
    public String value9() {
        return getTienimiSa();
    }

    @Override
    public Integer value10() {
        return getSource();
    }

    @Override
    public Integer value11() {
        return getTarget();
    }

    @Override
    public Double value12() {
        return getCost();
    }

    @Override
    public Double value13() {
        return getReverseCost();
    }

    @Override
    public LineString<C2D> value14() {
        return getGeom();
    }

    @Override
    public DrLinkkiRecord value1(Integer value) {
        setGid(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value2(String value) {
        setLinkId(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value3(Integer value) {
        setKuntakoodi(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value4(Integer value) {
        setLinkkityyp(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value5(Integer value) {
        setAjosuunta(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value6(Integer value) {
        setLinkTila(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value7(String value) {
        setTienimiSu(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value8(String value) {
        setTienimiRu(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value9(String value) {
        setTienimiSa(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value10(Integer value) {
        setSource(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value11(Integer value) {
        setTarget(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value12(Double value) {
        setCost(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value13(Double value) {
        setReverseCost(value);
        return this;
    }

    @Override
    public DrLinkkiRecord value14(LineString<C2D> value) {
        setGeom(value);
        return this;
    }

    @Override
    public DrLinkkiRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Integer value6, String value7, String value8, String value9, Integer value10, Integer value11, Double value12, Double value13, LineString<C2D> value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DrLinkkiRecord
     */
    public DrLinkkiRecord() {
        super(DrLinkki.DR_LINKKI);
    }

    /**
     * Create a detached, initialised DrLinkkiRecord
     */
    public DrLinkkiRecord(Integer gid, String linkId, Integer kuntakoodi, Integer linkkityyp, Integer ajosuunta, Integer linkTila, String tienimiSu, String tienimiRu, String tienimiSa, Integer source, Integer target, Double cost, Double reverseCost, LineString<C2D> geom) {
        super(DrLinkki.DR_LINKKI);

        setGid(gid);
        setLinkId(linkId);
        setKuntakoodi(kuntakoodi);
        setLinkkityyp(linkkityyp);
        setAjosuunta(ajosuunta);
        setLinkTila(linkTila);
        setTienimiSu(tienimiSu);
        setTienimiRu(tienimiRu);
        setTienimiSa(tienimiSa);
        setSource(source);
        setTarget(target);
        setCost(cost);
        setReverseCost(reverseCost);
        setGeom(geom);
    }
}
