/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model.tables.records;


import fi.hsl.jore4.mapmatching.model.tables.DrPysakki;

import org.geolatte.geom.C2D;
import org.geolatte.geom.Point;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrPysakkiRecord extends UpdatableRecordImpl<DrPysakkiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>routing.dr_pysakki.gid</code>.
     */
    public void setGid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.gid</code>.
     */
    public Integer getGid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>routing.dr_pysakki.link_id</code>.
     */
    public void setLinkId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.link_id</code>.
     */
    public String getLinkId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>routing.dr_pysakki.link_mmlid</code>.
     */
    public void setLinkMmlid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.link_mmlid</code>.
     */
    public String getLinkMmlid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>routing.dr_pysakki.valtak_id</code>.
     */
    public void setValtakId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.valtak_id</code>.
     */
    public Integer getValtakId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>routing.dr_pysakki.kuntakoodi</code>.
     */
    public void setKuntakoodi(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.kuntakoodi</code>.
     */
    public Integer getKuntakoodi() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>routing.dr_pysakki.koord_x</code>.
     */
    public void setKoordX(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.koord_x</code>.
     */
    public Double getKoordX() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>routing.dr_pysakki.koord_y</code>.
     */
    public void setKoordY(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.koord_y</code>.
     */
    public Double getKoordY() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>routing.dr_pysakki.sijainti_m</code>.
     */
    public void setSijaintiM(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.sijainti_m</code>.
     */
    public Double getSijaintiM() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>routing.dr_pysakki.vaik_suunt</code>.
     */
    public void setVaikSuunt(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.vaik_suunt</code>.
     */
    public Integer getVaikSuunt() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>routing.dr_pysakki.nimi_su</code>.
     */
    public void setNimiSu(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.nimi_su</code>.
     */
    public String getNimiSu() {
        return (String) get(9);
    }

    /**
     * Setter for <code>routing.dr_pysakki.nimi_ru</code>.
     */
    public void setNimiRu(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.nimi_ru</code>.
     */
    public String getNimiRu() {
        return (String) get(10);
    }

    /**
     * Setter for <code>routing.dr_pysakki.yllapitaja</code>.
     */
    public void setYllapitaja(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.yllapitaja</code>.
     */
    public Integer getYllapitaja() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>routing.dr_pysakki.yllap_tunn</code>.
     */
    public void setYllapTunn(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.yllap_tunn</code>.
     */
    public String getYllapTunn() {
        return (String) get(12);
    }

    /**
     * Setter for <code>routing.dr_pysakki.livi_tunn</code>.
     */
    public void setLiviTunn(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.livi_tunn</code>.
     */
    public String getLiviTunn() {
        return (String) get(13);
    }

    /**
     * Setter for <code>routing.dr_pysakki.matk_tunn</code>.
     */
    public void setMatkTunn(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.matk_tunn</code>.
     */
    public String getMatkTunn() {
        return (String) get(14);
    }

    /**
     * Setter for <code>routing.dr_pysakki.maast_x</code>.
     */
    public void setMaastX(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.maast_x</code>.
     */
    public String getMaastX() {
        return (String) get(15);
    }

    /**
     * Setter for <code>routing.dr_pysakki.maast_y</code>.
     */
    public void setMaastY(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.maast_y</code>.
     */
    public String getMaastY() {
        return (String) get(16);
    }

    /**
     * Setter for <code>routing.dr_pysakki.maast_z</code>.
     */
    public void setMaastZ(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.maast_z</code>.
     */
    public String getMaastZ() {
        return (String) get(17);
    }

    /**
     * Setter for <code>routing.dr_pysakki.liik_suunt</code>.
     */
    public void setLiikSuunt(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.liik_suunt</code>.
     */
    public String getLiikSuunt() {
        return (String) get(18);
    }

    /**
     * Setter for <code>routing.dr_pysakki.l_suuntima</code>.
     */
    public void setLSuuntima(Double value) {
        set(19, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.l_suuntima</code>.
     */
    public Double getLSuuntima() {
        return (Double) get(19);
    }

    /**
     * Setter for <code>routing.dr_pysakki.ens_vo_pv</code>.
     */
    public void setEnsVoPv(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.ens_vo_pv</code>.
     */
    public String getEnsVoPv() {
        return (String) get(20);
    }

    /**
     * Setter for <code>routing.dr_pysakki.viim_vo_pv</code>.
     */
    public void setViimVoPv(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.viim_vo_pv</code>.
     */
    public String getViimVoPv() {
        return (String) get(21);
    }

    /**
     * Setter for <code>routing.dr_pysakki.pys_tyyppi</code>.
     */
    public void setPysTyyppi(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.pys_tyyppi</code>.
     */
    public String getPysTyyppi() {
        return (String) get(22);
    }

    /**
     * Setter for <code>routing.dr_pysakki.aikataulu</code>.
     */
    public void setAikataulu(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.aikataulu</code>.
     */
    public Integer getAikataulu() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>routing.dr_pysakki.katos</code>.
     */
    public void setKatos(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.katos</code>.
     */
    public Integer getKatos() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>routing.dr_pysakki.penkki</code>.
     */
    public void setPenkki(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.penkki</code>.
     */
    public Integer getPenkki() {
        return (Integer) get(25);
    }

    /**
     * Setter for <code>routing.dr_pysakki.mainoskat</code>.
     */
    public void setMainoskat(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.mainoskat</code>.
     */
    public Integer getMainoskat() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>routing.dr_pysakki.pyoratelin</code>.
     */
    public void setPyoratelin(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.pyoratelin</code>.
     */
    public Integer getPyoratelin() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>routing.dr_pysakki.s_aikataul</code>.
     */
    public void setSAikataul(Integer value) {
        set(28, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.s_aikataul</code>.
     */
    public Integer getSAikataul() {
        return (Integer) get(28);
    }

    /**
     * Setter for <code>routing.dr_pysakki.valaistus</code>.
     */
    public void setValaistus(Integer value) {
        set(29, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.valaistus</code>.
     */
    public Integer getValaistus() {
        return (Integer) get(29);
    }

    /**
     * Setter for <code>routing.dr_pysakki.estettomyy</code>.
     */
    public void setEstettomyy(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.estettomyy</code>.
     */
    public String getEstettomyy() {
        return (String) get(30);
    }

    /**
     * Setter for <code>routing.dr_pysakki.saattomahd</code>.
     */
    public void setSaattomahd(Integer value) {
        set(31, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.saattomahd</code>.
     */
    public Integer getSaattomahd() {
        return (Integer) get(31);
    }

    /**
     * Setter for <code>routing.dr_pysakki.liit_lkm</code>.
     */
    public void setLiitLkm(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.liit_lkm</code>.
     */
    public String getLiitLkm() {
        return (String) get(32);
    }

    /**
     * Setter for <code>routing.dr_pysakki.liit_lisat</code>.
     */
    public void setLiitLisat(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.liit_lisat</code>.
     */
    public String getLiitLisat() {
        return (String) get(33);
    }

    /**
     * Setter for <code>routing.dr_pysakki.pys_omist</code>.
     */
    public void setPysOmist(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.pys_omist</code>.
     */
    public String getPysOmist() {
        return (String) get(34);
    }

    /**
     * Setter for <code>routing.dr_pysakki.palaute_os</code>.
     */
    public void setPalauteOs(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.palaute_os</code>.
     */
    public String getPalauteOs() {
        return (String) get(35);
    }

    /**
     * Setter for <code>routing.dr_pysakki.lisatiedot</code>.
     */
    public void setLisatiedot(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.lisatiedot</code>.
     */
    public String getLisatiedot() {
        return (String) get(36);
    }

    /**
     * Setter for <code>routing.dr_pysakki.irti_geom</code>.
     */
    public void setIrtiGeom(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.irti_geom</code>.
     */
    public Integer getIrtiGeom() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>routing.dr_pysakki.muokkauspv</code>.
     */
    public void setMuokkauspv(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.muokkauspv</code>.
     */
    public String getMuokkauspv() {
        return (String) get(38);
    }

    /**
     * Setter for <code>routing.dr_pysakki.laiturinum</code>.
     */
    public void setLaiturinum(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.laiturinum</code>.
     */
    public String getLaiturinum() {
        return (String) get(39);
    }

    /**
     * Setter for <code>routing.dr_pysakki.liit_term</code>.
     */
    public void setLiitTerm(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.liit_term</code>.
     */
    public String getLiitTerm() {
        return (String) get(40);
    }

    /**
     * Setter for <code>routing.dr_pysakki.vyohyktiet</code>.
     */
    public void setVyohyktiet(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.vyohyktiet</code>.
     */
    public String getVyohyktiet() {
        return (String) get(41);
    }

    /**
     * Setter for <code>routing.dr_pysakki.palvelutas</code>.
     */
    public void setPalvelutas(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.palvelutas</code>.
     */
    public String getPalvelutas() {
        return (String) get(42);
    }

    /**
     * Setter for <code>routing.dr_pysakki.geom</code>.
     */
    public void setGeom(Point<C2D> value) {
        set(43, value);
    }

    /**
     * Getter for <code>routing.dr_pysakki.geom</code>.
     */
    public Point<C2D> getGeom() {
        return (Point<C2D>) get(43);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DrPysakkiRecord
     */
    public DrPysakkiRecord() {
        super(DrPysakki.DR_PYSAKKI);
    }

    /**
     * Create a detached, initialised DrPysakkiRecord
     */
    public DrPysakkiRecord(Integer gid, String linkId, String linkMmlid, Integer valtakId, Integer kuntakoodi, Double koordX, Double koordY, Double sijaintiM, Integer vaikSuunt, String nimiSu, String nimiRu, Integer yllapitaja, String yllapTunn, String liviTunn, String matkTunn, String maastX, String maastY, String maastZ, String liikSuunt, Double lSuuntima, String ensVoPv, String viimVoPv, String pysTyyppi, Integer aikataulu, Integer katos, Integer penkki, Integer mainoskat, Integer pyoratelin, Integer sAikataul, Integer valaistus, String estettomyy, Integer saattomahd, String liitLkm, String liitLisat, String pysOmist, String palauteOs, String lisatiedot, Integer irtiGeom, String muokkauspv, String laiturinum, String liitTerm, String vyohyktiet, String palvelutas, Point<C2D> geom) {
        super(DrPysakki.DR_PYSAKKI);

        setGid(gid);
        setLinkId(linkId);
        setLinkMmlid(linkMmlid);
        setValtakId(valtakId);
        setKuntakoodi(kuntakoodi);
        setKoordX(koordX);
        setKoordY(koordY);
        setSijaintiM(sijaintiM);
        setVaikSuunt(vaikSuunt);
        setNimiSu(nimiSu);
        setNimiRu(nimiRu);
        setYllapitaja(yllapitaja);
        setYllapTunn(yllapTunn);
        setLiviTunn(liviTunn);
        setMatkTunn(matkTunn);
        setMaastX(maastX);
        setMaastY(maastY);
        setMaastZ(maastZ);
        setLiikSuunt(liikSuunt);
        setLSuuntima(lSuuntima);
        setEnsVoPv(ensVoPv);
        setViimVoPv(viimVoPv);
        setPysTyyppi(pysTyyppi);
        setAikataulu(aikataulu);
        setKatos(katos);
        setPenkki(penkki);
        setMainoskat(mainoskat);
        setPyoratelin(pyoratelin);
        setSAikataul(sAikataul);
        setValaistus(valaistus);
        setEstettomyy(estettomyy);
        setSaattomahd(saattomahd);
        setLiitLkm(liitLkm);
        setLiitLisat(liitLisat);
        setPysOmist(pysOmist);
        setPalauteOs(palauteOs);
        setLisatiedot(lisatiedot);
        setIrtiGeom(irtiGeom);
        setMuokkauspv(muokkauspv);
        setLaiturinum(laiturinum);
        setLiitTerm(liitTerm);
        setVyohyktiet(vyohyktiet);
        setPalvelutas(palvelutas);
        setGeom(geom);
    }
}
