/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model.tables;


import fi.hsl.jore4.mapmatching.model.Keys;
import fi.hsl.jore4.mapmatching.model.Routing;
import fi.hsl.jore4.mapmatching.model.tables.records.DrLinkkiRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrLinkki extends TableImpl<DrLinkkiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>routing.dr_linkki</code>
     */
    public static final DrLinkki DR_LINKKI = new DrLinkki();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DrLinkkiRecord> getRecordType() {
        return DrLinkkiRecord.class;
    }

    /**
     * The column <code>routing.dr_linkki.gid</code>.
     */
    public final TableField<DrLinkkiRecord, Integer> GID = createField(DSL.name("gid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_linkki.link_id</code>.
     */
    public final TableField<DrLinkkiRecord, String> LINK_ID = createField(DSL.name("link_id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>routing.dr_linkki.kuntakoodi</code>.
     */
    public final TableField<DrLinkkiRecord, Integer> KUNTAKOODI = createField(DSL.name("kuntakoodi"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_linkki.linkkityyp</code>.
     */
    public final TableField<DrLinkkiRecord, Integer> LINKKITYYP = createField(DSL.name("linkkityyp"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_linkki.ajosuunta</code>.
     */
    public final TableField<DrLinkkiRecord, Integer> AJOSUUNTA = createField(DSL.name("ajosuunta"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_linkki.link_tila</code>.
     */
    public final TableField<DrLinkkiRecord, Integer> LINK_TILA = createField(DSL.name("link_tila"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_linkki.tienimi_su</code>.
     */
    public final TableField<DrLinkkiRecord, String> TIENIMI_SU = createField(DSL.name("tienimi_su"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_linkki.tienimi_ru</code>.
     */
    public final TableField<DrLinkkiRecord, String> TIENIMI_RU = createField(DSL.name("tienimi_ru"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_linkki.tienimi_sa</code>.
     */
    public final TableField<DrLinkkiRecord, String> TIENIMI_SA = createField(DSL.name("tienimi_sa"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_linkki.source</code>.
     */
    public final TableField<DrLinkkiRecord, Integer> SOURCE = createField(DSL.name("source"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_linkki.target</code>.
     */
    public final TableField<DrLinkkiRecord, Integer> TARGET = createField(DSL.name("target"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_linkki.cost</code>.
     */
    public final TableField<DrLinkkiRecord, Double> COST = createField(DSL.name("cost"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>routing.dr_linkki.reverse_cost</code>.
     */
    public final TableField<DrLinkkiRecord, Double> REVERSE_COST = createField(DSL.name("reverse_cost"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<DrLinkkiRecord, Object> GEOM = createField(DSL.name("geom"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"extensions\".\"geometry\"").nullable(false), this, "");

    private DrLinkki(Name alias, Table<DrLinkkiRecord> aliased) {
        this(alias, aliased, null);
    }

    private DrLinkki(Name alias, Table<DrLinkkiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>routing.dr_linkki</code> table reference
     */
    public DrLinkki(String alias) {
        this(DSL.name(alias), DR_LINKKI);
    }

    /**
     * Create an aliased <code>routing.dr_linkki</code> table reference
     */
    public DrLinkki(Name alias) {
        this(alias, DR_LINKKI);
    }

    /**
     * Create a <code>routing.dr_linkki</code> table reference
     */
    public DrLinkki() {
        this(DSL.name("dr_linkki"), null);
    }

    public <O extends Record> DrLinkki(Table<O> child, ForeignKey<O, DrLinkkiRecord> key) {
        super(child, key, DR_LINKKI);
    }

    @Override
    public Schema getSchema() {
        return Routing.ROUTING;
    }

    @Override
    public UniqueKey<DrLinkkiRecord> getPrimaryKey() {
        return Keys.DR_LINKKI_PKEY;
    }

    @Override
    public List<UniqueKey<DrLinkkiRecord>> getKeys() {
        return Arrays.<UniqueKey<DrLinkkiRecord>>asList(Keys.DR_LINKKI_PKEY, Keys.UK_DR_LINKKI_LINK_ID);
    }

    @Override
    public DrLinkki as(String alias) {
        return new DrLinkki(DSL.name(alias), this);
    }

    @Override
    public DrLinkki as(Name alias) {
        return new DrLinkki(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DrLinkki rename(String name) {
        return new DrLinkki(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DrLinkki rename(Name name) {
        return new DrLinkki(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, String, Integer, Integer, Integer, Integer, String, String, String, Integer, Integer, Double, Double, Object> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
