/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model.tables;


import fi.hsl.jore4.mapmatching.config.jooq.converter.PointBinding;
import fi.hsl.jore4.mapmatching.model.Keys;
import fi.hsl.jore4.mapmatching.model.Routing;
import fi.hsl.jore4.mapmatching.model.tables.records.DrLinkkiVerticesPgrRecord;

import java.util.Arrays;
import java.util.List;

import org.geolatte.geom.C2D;
import org.geolatte.geom.Point;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrLinkkiVerticesPgr extends TableImpl<DrLinkkiVerticesPgrRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>routing.dr_linkki_vertices_pgr</code>
     */
    public static final DrLinkkiVerticesPgr DR_LINKKI_VERTICES_PGR = new DrLinkkiVerticesPgr();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DrLinkkiVerticesPgrRecord> getRecordType() {
        return DrLinkkiVerticesPgrRecord.class;
    }

    /**
     * The column <code>routing.dr_linkki_vertices_pgr.id</code>.
     */
    public final TableField<DrLinkkiVerticesPgrRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>routing.dr_linkki_vertices_pgr.cnt</code>.
     */
    public final TableField<DrLinkkiVerticesPgrRecord, Integer> CNT = createField(DSL.name("cnt"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_linkki_vertices_pgr.chk</code>.
     */
    public final TableField<DrLinkkiVerticesPgrRecord, Integer> CHK = createField(DSL.name("chk"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_linkki_vertices_pgr.ein</code>.
     */
    public final TableField<DrLinkkiVerticesPgrRecord, Integer> EIN = createField(DSL.name("ein"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_linkki_vertices_pgr.eout</code>.
     */
    public final TableField<DrLinkkiVerticesPgrRecord, Integer> EOUT = createField(DSL.name("eout"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_linkki_vertices_pgr.the_geom</code>.
     */
    public final TableField<DrLinkkiVerticesPgrRecord, Point<C2D>> THE_GEOM = createField(DSL.name("the_geom"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"extensions\".\"geometry\""), this, "", new PointBinding());

    private DrLinkkiVerticesPgr(Name alias, Table<DrLinkkiVerticesPgrRecord> aliased) {
        this(alias, aliased, null);
    }

    private DrLinkkiVerticesPgr(Name alias, Table<DrLinkkiVerticesPgrRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>routing.dr_linkki_vertices_pgr</code> table reference
     */
    public DrLinkkiVerticesPgr(String alias) {
        this(DSL.name(alias), DR_LINKKI_VERTICES_PGR);
    }

    /**
     * Create an aliased <code>routing.dr_linkki_vertices_pgr</code> table reference
     */
    public DrLinkkiVerticesPgr(Name alias) {
        this(alias, DR_LINKKI_VERTICES_PGR);
    }

    /**
     * Create a <code>routing.dr_linkki_vertices_pgr</code> table reference
     */
    public DrLinkkiVerticesPgr() {
        this(DSL.name("dr_linkki_vertices_pgr"), null);
    }

    public <O extends Record> DrLinkkiVerticesPgr(Table<O> child, ForeignKey<O, DrLinkkiVerticesPgrRecord> key) {
        super(child, key, DR_LINKKI_VERTICES_PGR);
    }

    @Override
    public Schema getSchema() {
        return Routing.ROUTING;
    }

    @Override
    public Identity<DrLinkkiVerticesPgrRecord, Long> getIdentity() {
        return (Identity<DrLinkkiVerticesPgrRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DrLinkkiVerticesPgrRecord> getPrimaryKey() {
        return Keys.DR_LINKKI_VERTICES_PGR_PKEY;
    }

    @Override
    public List<UniqueKey<DrLinkkiVerticesPgrRecord>> getKeys() {
        return Arrays.<UniqueKey<DrLinkkiVerticesPgrRecord>>asList(Keys.DR_LINKKI_VERTICES_PGR_PKEY);
    }

    @Override
    public DrLinkkiVerticesPgr as(String alias) {
        return new DrLinkkiVerticesPgr(DSL.name(alias), this);
    }

    @Override
    public DrLinkkiVerticesPgr as(Name alias) {
        return new DrLinkkiVerticesPgr(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DrLinkkiVerticesPgr rename(String name) {
        return new DrLinkkiVerticesPgr(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DrLinkkiVerticesPgr rename(Name name) {
        return new DrLinkkiVerticesPgr(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Integer, Integer, Integer, Integer, Point<C2D>> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
