/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore4.mapmatching.model.tables;


import fi.hsl.jore4.mapmatching.config.jooq.converter.PointBinding;
import fi.hsl.jore4.mapmatching.model.Keys;
import fi.hsl.jore4.mapmatching.model.Routing;
import fi.hsl.jore4.mapmatching.model.tables.records.DrPysakkiRecord;

import java.util.Arrays;
import java.util.List;

import org.geolatte.geom.C2D;
import org.geolatte.geom.Point;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrPysakki extends TableImpl<DrPysakkiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>routing.dr_pysakki</code>
     */
    public static final DrPysakki DR_PYSAKKI = new DrPysakki();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DrPysakkiRecord> getRecordType() {
        return DrPysakkiRecord.class;
    }

    /**
     * The column <code>routing.dr_pysakki.gid</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> GID = createField(DSL.name("gid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_pysakki.link_id</code>.
     */
    public final TableField<DrPysakkiRecord, String> LINK_ID = createField(DSL.name("link_id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>routing.dr_pysakki.link_mmlid</code>.
     */
    public final TableField<DrPysakkiRecord, String> LINK_MMLID = createField(DSL.name("link_mmlid"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>routing.dr_pysakki.valtak_id</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> VALTAK_ID = createField(DSL.name("valtak_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_pysakki.kuntakoodi</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> KUNTAKOODI = createField(DSL.name("kuntakoodi"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_pysakki.koord_x</code>.
     */
    public final TableField<DrPysakkiRecord, Double> KOORD_X = createField(DSL.name("koord_x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>routing.dr_pysakki.koord_y</code>.
     */
    public final TableField<DrPysakkiRecord, Double> KOORD_Y = createField(DSL.name("koord_y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>routing.dr_pysakki.sijainti_m</code>.
     */
    public final TableField<DrPysakkiRecord, Double> SIJAINTI_M = createField(DSL.name("sijainti_m"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>routing.dr_pysakki.vaik_suunt</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> VAIK_SUUNT = createField(DSL.name("vaik_suunt"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>routing.dr_pysakki.nimi_su</code>.
     */
    public final TableField<DrPysakkiRecord, String> NIMI_SU = createField(DSL.name("nimi_su"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.nimi_ru</code>.
     */
    public final TableField<DrPysakkiRecord, String> NIMI_RU = createField(DSL.name("nimi_ru"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.yllapitaja</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> YLLAPITAJA = createField(DSL.name("yllapitaja"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.yllap_tunn</code>.
     */
    public final TableField<DrPysakkiRecord, String> YLLAP_TUNN = createField(DSL.name("yllap_tunn"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>routing.dr_pysakki.livi_tunn</code>.
     */
    public final TableField<DrPysakkiRecord, String> LIVI_TUNN = createField(DSL.name("livi_tunn"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>routing.dr_pysakki.matk_tunn</code>.
     */
    public final TableField<DrPysakkiRecord, String> MATK_TUNN = createField(DSL.name("matk_tunn"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>routing.dr_pysakki.maast_x</code>.
     */
    public final TableField<DrPysakkiRecord, String> MAAST_X = createField(DSL.name("maast_x"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>routing.dr_pysakki.maast_y</code>.
     */
    public final TableField<DrPysakkiRecord, String> MAAST_Y = createField(DSL.name("maast_y"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>routing.dr_pysakki.maast_z</code>.
     */
    public final TableField<DrPysakkiRecord, String> MAAST_Z = createField(DSL.name("maast_z"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>routing.dr_pysakki.liik_suunt</code>.
     */
    public final TableField<DrPysakkiRecord, String> LIIK_SUUNT = createField(DSL.name("liik_suunt"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.l_suuntima</code>.
     */
    public final TableField<DrPysakkiRecord, Double> L_SUUNTIMA = createField(DSL.name("l_suuntima"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>routing.dr_pysakki.ens_vo_pv</code>.
     */
    public final TableField<DrPysakkiRecord, String> ENS_VO_PV = createField(DSL.name("ens_vo_pv"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>routing.dr_pysakki.viim_vo_pv</code>.
     */
    public final TableField<DrPysakkiRecord, String> VIIM_VO_PV = createField(DSL.name("viim_vo_pv"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>routing.dr_pysakki.pys_tyyppi</code>.
     */
    public final TableField<DrPysakkiRecord, String> PYS_TYYPPI = createField(DSL.name("pys_tyyppi"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>routing.dr_pysakki.aikataulu</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> AIKATAULU = createField(DSL.name("aikataulu"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.katos</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> KATOS = createField(DSL.name("katos"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.penkki</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> PENKKI = createField(DSL.name("penkki"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.mainoskat</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> MAINOSKAT = createField(DSL.name("mainoskat"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.pyoratelin</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> PYORATELIN = createField(DSL.name("pyoratelin"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.s_aikataul</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> S_AIKATAUL = createField(DSL.name("s_aikataul"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.valaistus</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> VALAISTUS = createField(DSL.name("valaistus"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.estettomyy</code>.
     */
    public final TableField<DrPysakkiRecord, String> ESTETTOMYY = createField(DSL.name("estettomyy"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.saattomahd</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> SAATTOMAHD = createField(DSL.name("saattomahd"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.liit_lkm</code>.
     */
    public final TableField<DrPysakkiRecord, String> LIIT_LKM = createField(DSL.name("liit_lkm"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.liit_lisat</code>.
     */
    public final TableField<DrPysakkiRecord, String> LIIT_LISAT = createField(DSL.name("liit_lisat"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.pys_omist</code>.
     */
    public final TableField<DrPysakkiRecord, String> PYS_OMIST = createField(DSL.name("pys_omist"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.palaute_os</code>.
     */
    public final TableField<DrPysakkiRecord, String> PALAUTE_OS = createField(DSL.name("palaute_os"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.lisatiedot</code>.
     */
    public final TableField<DrPysakkiRecord, String> LISATIEDOT = createField(DSL.name("lisatiedot"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.irti_geom</code>.
     */
    public final TableField<DrPysakkiRecord, Integer> IRTI_GEOM = createField(DSL.name("irti_geom"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>routing.dr_pysakki.muokkauspv</code>.
     */
    public final TableField<DrPysakkiRecord, String> MUOKKAUSPV = createField(DSL.name("muokkauspv"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>routing.dr_pysakki.laiturinum</code>.
     */
    public final TableField<DrPysakkiRecord, String> LAITURINUM = createField(DSL.name("laiturinum"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.liit_term</code>.
     */
    public final TableField<DrPysakkiRecord, String> LIIT_TERM = createField(DSL.name("liit_term"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.vyohyktiet</code>.
     */
    public final TableField<DrPysakkiRecord, String> VYOHYKTIET = createField(DSL.name("vyohyktiet"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.palvelutas</code>.
     */
    public final TableField<DrPysakkiRecord, String> PALVELUTAS = createField(DSL.name("palvelutas"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>routing.dr_pysakki.geom</code>.
     */
    public final TableField<DrPysakkiRecord, Point<C2D>> GEOM = createField(DSL.name("geom"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"extensions\".\"geometry\"").nullable(false), this, "", new PointBinding());

    private DrPysakki(Name alias, Table<DrPysakkiRecord> aliased) {
        this(alias, aliased, null);
    }

    private DrPysakki(Name alias, Table<DrPysakkiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>routing.dr_pysakki</code> table reference
     */
    public DrPysakki(String alias) {
        this(DSL.name(alias), DR_PYSAKKI);
    }

    /**
     * Create an aliased <code>routing.dr_pysakki</code> table reference
     */
    public DrPysakki(Name alias) {
        this(alias, DR_PYSAKKI);
    }

    /**
     * Create a <code>routing.dr_pysakki</code> table reference
     */
    public DrPysakki() {
        this(DSL.name("dr_pysakki"), null);
    }

    public <O extends Record> DrPysakki(Table<O> child, ForeignKey<O, DrPysakkiRecord> key) {
        super(child, key, DR_PYSAKKI);
    }

    @Override
    public Schema getSchema() {
        return Routing.ROUTING;
    }

    @Override
    public UniqueKey<DrPysakkiRecord> getPrimaryKey() {
        return Keys.DR_PYSAKKI_PKEY;
    }

    @Override
    public List<UniqueKey<DrPysakkiRecord>> getKeys() {
        return Arrays.<UniqueKey<DrPysakkiRecord>>asList(Keys.DR_PYSAKKI_PKEY);
    }

    @Override
    public List<ForeignKey<DrPysakkiRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DrPysakkiRecord, ?>>asList(Keys.DR_PYSAKKI__FK_DR_PYSAKKI_LINK_ID);
    }

    private transient DrLinkki _drLinkki;

    public DrLinkki drLinkki() {
        if (_drLinkki == null)
            _drLinkki = new DrLinkki(this, Keys.DR_PYSAKKI__FK_DR_PYSAKKI_LINK_ID);

        return _drLinkki;
    }

    @Override
    public DrPysakki as(String alias) {
        return new DrPysakki(DSL.name(alias), this);
    }

    @Override
    public DrPysakki as(Name alias) {
        return new DrPysakki(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DrPysakki rename(String name) {
        return new DrPysakki(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DrPysakki rename(Name name) {
        return new DrPysakki(name, null);
    }
}
