name: CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run_kotlin_tests:
    name: Run Kotlin tests
    uses: ./.github/workflows/run-kotlin-tests.yml

  publish_docker_image_to_docker_hub:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-24.04
    needs: run_kotlin_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: Pull previous images to support caching
        run: |
          docker pull $IMAGE_NAME:builder || >&2 echo "Previous builder image not found"
          docker pull $IMAGE_NAME:latest || >&2 echo "Previous image not found"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.JORE4_DOCKERHUB_USER }}
          password: ${{ secrets.JORE4_DOCKERHUB_TOKEN }}

      - name: Build and push image tagged with commit ID to Docker Hub
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --cache-from=$IMAGE_NAME:builder \
            --cache-from=$IMAGE_NAME:latest \
            -t $IMAGE_NAME:$COMMIT_ID \
            .

      - name: Build and push :builder and :latest tag to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --target builder \
            --cache-from=$IMAGE_NAME:builder \
            -t $IMAGE_NAME:builder \
            .

          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --cache-from=$IMAGE_NAME:builder \
            --cache-from=$IMAGE_NAME:latest \
            -t $IMAGE_NAME:latest \
            .

  publish_docker_image_to_acr:
    needs:
      - run_kotlin_tests
    name: Publish Docker image to ACR
    permissions:
      id-token: write
      contents: read
    uses: HSLdevcom/jore4-tools/.github/workflows/shared-build-and-publish-docker-image.yml@shared-build-and-publish-docker-image-v1
    with:
      docker_image_name: jore4-map-matching
      build_arm64_image: true
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  run_e2e_tests:
    runs-on: ubuntu-24.04
    needs:
      - run_kotlin_tests
      - publish_docker_image_to_acr
    steps:
      - name: Run e2e tests
        uses: HSLdevcom/jore4-tools/github-actions/run-ci@main
        with:
          mapmatching_version: "${{ needs.publish_docker_image_to_acr.outputs.docker_image }}"
