name: Generate jooq

on:
  push:
  pull_request:
    branches: [main]

jobs:
  generate-jooq:
    name: Verifies whether generated jooq classes have been updated
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          java-package: jdk
          architecture: x64
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run jOOQ class generation
        run: |
          # create mandatory Maven configuration file for runner user
          RUNNER_USERNAME=$(whoami)
          touch ./spring-boot/profiles/dev/config.${RUNNER_USERNAME}.properties

          # generate jOOQ classes
          ./development.sh generate:jooq

      - name: Verify that workspace is clean, so jOOQ classes are up to date
        run: '[ -z "$(git status --porcelain)" ]'
