name: Generate jooq

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-jooq:
    name: Verifies whether generated jooq classes have been updated
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          java-package: jdk
          architecture: x64
          distribution: temurin
          cache: maven

      - name: Run jOOQ class generation
        run: |
          # create mandatory Maven configuration file for runner user
          RUNNER_USERNAME=$(whoami)
          touch ./spring-boot/profiles/dev/config.${RUNNER_USERNAME}.properties

          # generate jOOQ classes
          ./development.sh generate:jooq

      - name: Verify that workspace is clean, so jOOQ classes are up to date
        run: '[ -z "$(git status --porcelain)" ]'
