name: Run java tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run java tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start test environment in the background
        run: ./development.sh start:deps

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests and try building a package
        run: |
          # create mvn profile for runner user
          RUNNER_USERNAME=$(whoami)
          cp ./spring-boot/profiles/dev/config.properties ./spring-boot/profiles/dev/config.${RUNNER_USERNAME}.properties

          # run tests
          cd ./spring-boot && mvn clean verify
