name: Test whether the dockerized version works

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-docker-compose:
    name: Verify Docker Compose setup
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start the database and the map-matching service
        run: ./development.sh start

      - name: Verify that dockerized map-matching API is up and running
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          command:
            "curl --fail http://localhost:3005/actuator/health --output
            /dev/null --silent"
